### ISSUE TITLE
Training Bug ---- ValueError: Minimum image value is not finite

### ISSUE THREAD

**Issue by Shi-qingyu** [EnVision-Research/MotionInversion#10]
Thank you for your great work and contribution to the open-source community!
I changed the `line 293` in `train.py`  to: 
`unet = UNet3DConditionModel.from_pretrained("adamdad/videocrafterv2_diffusers", torch_dtype=torch.float16)`
After this change, when I run:
`python train.py --config ./configs/config.yaml`
I encounter a problem during the validation step:
```
Traceback (most recent call last):████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:16<00:00,  1.84it/s]
  File "/home/sqy/PythonProjects/diffusion/MotionInversion/train.py", line 477, in <module>
    main(config)
  File "/home/sqy/PythonProjects/diffusion/MotionInversion/train.py", line 421, in main
    log_validation(
  File "/home/sqy/PythonProjects/diffusion/MotionInversion/train.py", line 96, in log_validation
    export_to_video(video_frames, os.path.join(file_path, file_name), config.dataset.fps)
  File "/home/sqy/PythonProjects/diffusion/MotionInversion/train.py", line 120, in export_to_video
    video_writer.append_data(np.array(img))
  File "/home/sqy/miniconda3/envs/motion_inversion/lib/python3.10/site-packages/imageio/core/format.py", line 590, in append_data
    return self._append_data(im, total_meta)
  File "/home/sqy/miniconda3/envs/motion_inversion/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 570, in _append_data
    im = image_as_uint(im, bitdepth=8)
  File "/home/sqy/miniconda3/envs/motion_inversion/lib/python3.10/site-packages/imageio/core/util.py", line 96, in image_as_uint
    raise ValueError("Minimum image value is not finite")
ValueError: Minimum image value is not finite
```
While using UNet from Zeroscope for training and VideoCrafterv2 for inference yields promising results, I'm still curious about the outcomes of training directly with VideoCrafterv2.

**Comment by ziyang1106** [comment]
Hi Qingyu, thank you for supporting our work.

The issue is directly caused by the generated video has negative or infinite pixel value, which might be a result of mixture using of different unets (for example, VideoCrafter2 for training and Zeroscope for inference). It's recommended to use same unet at different stages for better performance.

Pls kindly check if you have changed `line 15` in `configs/config.yaml` from `unet:  zeroscope_v2_576w` to `unet:  VideoCrafter2`. By doing this, the code will automatically align unet setting at different stages.

Btw, the default setting of our code is using only VideoCrafter2 for both training and inference. If no modification is made to the code except model path, the outcome should be good.

If still don't work, pls report the detailed config setting. Thanks.

**Comment by Shi-qingyu** [comment]
Hi Ziyang,

Thank you for your reply! I followed your advice and made the necessary adjustments in the `config.yaml` file to ensure consistency in the U-Net setting. This resolved the issue, and the video generation is now working as expected.

Please feel free to close this issue.

**Comment by ziyang1106** [comment]
Great to hear that!  Wish you the best in your research!
